### ISSUE TITLE
Switch to links api

### ISSUE THREAD

**Issue by bastian-friedrich** [cheers-io/nuxt-storyblok-sitemap#14]
As I see we are using stories API to fetch data from storyblok. Doesn't it make sense to switch to links API instead as mentioned here? https://www.storyblok.com/tp/how-to-generate-sitemap-headless-cms?_ampify=1

**Comment by sumerokr** [comment]
Hey, I have checked them already. Links don't have published time, therefore we have no data to generate `lastmod` node.
