### ISSUE TITLE
Consider deleting the defaultLocale configuration parameter

### ISSUE THREAD

**Issue by sumerokr** [cheers-io/nuxt-storyblok-sitemap#5]
Currently, the `defaultLocale` parameter is required for the module to work.

What if the user's project is not multilingual? If it's a single language project, there is no need for the locale and it's not used in the sitemap. Or we can get it (when needed) from the Storyblok API in a runtime.

**AC**
- check the [guideline](https://developers.google.com/search/docs/specialty/international/localized-versions#sitemap)
- check [Storyblok docs](https://www.storyblok.com/docs/api/content-delivery/v2#core-resources/spaces/spaces)
- make a decision if `defaultLocale` should be required
- if needed, adjust the logic accordingly

**Comment by bastian-friedrich** [comment]
If it is possible to get the default language from storyblok, we should do it. If it's not possible, then no `defaultLocale` means no multilanguage sitemap.
